### 성공로그인요청
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "user0",
  "password": "1234"
}

### eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMCIsImlhdCI6MTc1MDgzMTg2MiwiZXhwIjoxNzUwODMyMTYyfQ.05DSwNfv3He2xKEiOeOyT4TfvjiotVMCOsRhMfXdy34

### 공개 엔드포인트 접근
GET http://localhost:8080/api/security/all